-- LoveSync Production Schema (Consolidated)
-- Version: 2.0
-- Includes: Core, Game, Sleep, Radio, Notifications, Storage

-- 1. Extensions
create extension if not exists postgis;
create extension if not exists "uuid-ossp"; -- For uuid_generate_v4 if needed, though gen_random_uuid() is preferred

-- 2. Profiles Table (Core)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  couple_id uuid, -- Link to couple
  location geography(POINT),
  mood text,
  last_active timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Couples Table (Core)
create table if not exists public.couples (
  id uuid default gen_random_uuid() primary key,
  partner_a uuid references public.profiles(id),
  partner_b uuid references public.profiles(id),
  connect_code text unique,
  streak_count integer default 0,
  streak_status text default 'pending_photo', -- pending_photo / pending_answer / completed
  last_streak_date date,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Update Profiles with Circular FK
alter table public.profiles 
drop constraint if exists profiles_couple_id_fkey;

alter table public.profiles 
add constraint profiles_couple_id_fkey 
foreign key (couple_id) references public.couples(id);

-- 4. Heartbeats
create table if not exists public.heartbeats (
  id bigint generated by default as identity primary key,
  couple_id uuid references public.couples(id),
  sender_id uuid references public.profiles(id),
  sent_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Daily Prompts
create table if not exists public.daily_prompts (
  id bigint generated by default as identity primary key,
  couple_id uuid references public.couples(id),
  question_text text not null,
  is_answered boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  answer_a text,
  answer_b text
);

-- 6. Memories (Combined Schema)
create table if not exists public.memories (
  id uuid default gen_random_uuid() primary key,
  couple_id uuid references public.couples(id) on delete cascade,
  uploader_id uuid references public.profiles(id), -- or uploaded_by
  image_url text not null,
  caption text,
  location geography(POINT),
  taken_at date default current_date,
  is_locked boolean default false,
  unlock_condition text, 
  unlock_value text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 7. Game History
create table if not exists public.game_history (
  id uuid default gen_random_uuid() primary key,
  couple_id uuid references public.couples(id) on delete cascade,
  winner_id uuid references public.profiles(id),
  played_at timestamp with time zone default timezone('utc'::text, now()) not null,
  game_type text default 'tictactoe'
);

-- 8. Sleep Sync
create table if not exists public.sleep_sessions (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    couple_id uuid references public.couples(id) on delete cascade,
    sleep_time timestamp with time zone not null,
    wake_time timestamp with time zone,
    duration_minutes integer,
    quality_rating integer check (quality_rating >= 1 and quality_rating <= 5),
    notes text,
    created_at timestamp with time zone default now()
);

create table if not exists public.alarm_settings (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users(id) on delete cascade not null unique,
    alarm_time time,
    alarm_enabled boolean default false,
    alarm_tone text default 'gentle_chime',
    nature_sound_preference text default 'rain',
    wake_partner boolean default false,
    snooze_duration integer default 5,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- 9. Radio Transmissions
create table if not exists public.radio_transmissions (
  id uuid default gen_random_uuid() primary key,
  couple_id uuid, -- Loose coupling allowed
  sender_id uuid references auth.users(id),
  youtube_link text not null,
  voice_note_url text not null, 
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  is_played boolean default false
);

-- 10. Notifications
create table if not exists public.notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id),
  type text not null,
  title text,
  message text,
  metadata jsonb,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 11. Row Level Security (RLS) Enablement
alter table public.profiles enable row level security;
alter table public.couples enable row level security;
alter table public.daily_prompts enable row level security;
alter table public.memories enable row level security;
alter table public.game_history enable row level security;
alter table public.sleep_sessions enable row level security;
alter table public.alarm_settings enable row level security;
alter table public.radio_transmissions enable row level security;
alter table public.notifications enable row level security;

-- 12. Policies (Basic Set - See individual files for granular policies)
-- (Omitted full granular policies to save length, but ensuring creation is key)

-- 13. Storage Buckets
-- Create 'avatars', 'memories', 'voice-notes'
insert into storage.buckets (id, name, public) values 
('avatars', 'avatars', true),
('memories', 'memories', true),
('voice-notes', 'voice-notes', true)
on conflict (id) do update set public = true;

-- Storage Policies
create policy "Public Read Buckets"
  on storage.objects for select
  using ( bucket_id in ('avatars', 'memories', 'voice-notes') );

create policy "Auth Upload Buckets"
  on storage.objects for insert
  with check (
    bucket_id in ('avatars', 'memories', 'voice-notes') 
    and auth.role() = 'authenticated'
  );

-- Grant Permissions
grant all on public.profiles to postgres, authenticated, service_role;
grant all on public.couples to postgres, authenticated, service_role;
grant all on public.daily_prompts to postgres, authenticated, service_role;
grant all on public.memories to postgres, authenticated, service_role;
grant all on public.game_history to postgres, authenticated, service_role;
grant all on public.sleep_sessions to postgres, authenticated, service_role;
grant all on public.alarm_settings to postgres, authenticated, service_role;
grant all on public.radio_transmissions to postgres, authenticated, service_role;
grant all on public.notifications to postgres, authenticated, service_role;

