-- LoveSync Core Schema

-- Enable PostGIS for location features
create extension if not exists postgis;

-- 1. Profiles Table
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text, -- master face image
  couple_id uuid, -- FK added later
  location geography(POINT),
  mood text,
  last_active timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Couples Table
create table public.couples (
  id uuid default gen_random_uuid() primary key,
  partner_a uuid references public.profiles(id),
  partner_b uuid references public.profiles(id),
  connect_code text unique,
  streak_count integer default 0,
  streak_status text default 'pending_photo', -- pending_photo | pending_answer | completed
  last_streak_date date,
  created_at timestamp with time zone default timezone('utc'::text, now())

  -- Constraint: ensure partners are distinct (handled in app logic or complex constraint)
);

-- Circular FK update for profiles
alter table public.profiles 
add constraint profiles_couple_id_fkey 
foreign key (couple_id) references public.couples(id);

-- 3. Heartbeats (Realtime only, typically doesn't need persistence but we can log it)
-- We will use Supabase Realtime channels for this, no table needed strictly, 
-- but a log table is good for "last heartbeat" stats.
create table public.heartbeats (
  id bigint generated by default as identity primary key,
  couple_id uuid references public.couples(id),
  sender_id uuid references public.profiles(id),
  sent_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Daily Prompts / AI Questions
create table public.daily_prompts (
  id bigint generated by default as identity primary key,
  couple_id uuid references public.couples(id),
  question_text text not null,
  is_answered boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  answer_a text,
  answer_b text
);

-- 5. Photos / Memories (for Scavenger Hunt & Streaks)
create table public.memories (
  id uuid default gen_random_uuid() primary key,
  couple_id uuid references public.couples(id),
  uploader_id uuid references public.profiles(id),
  image_url text not null,
  caption text,
  location geography(POINT),
  is_locked boolean default false,
  unlock_condition text, -- e.g., 'radius' or 'time'
  unlock_value text, -- radius in meters or timestamp
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Row Level Security (RLS)
-- Enable RLS
alter table public.profiles enable row level security;
alter table public.couples enable row level security;
alter table public.daily_prompts enable row level security;
alter table public.memories enable row level security;

-- Policies (Simplified for initial setup)
-- Profiles: Users can see their own profile and their partner's profile.
-- Just allowing public read for authenticated users for now for simplicity in dev, 
-- but write restricted to self.
create policy "Public profiles are viewable by everyone" 
on public.profiles for select using ( true );

create policy "Users can update own profile" 
on public.profiles for update using ( auth.uid() = id );

-- Couples: Viewable by partners.
create policy "Couples viewable by partners"
on public.couples for select 
using ( auth.uid() = partner_a or auth.uid() = partner_b );

-- Storage Buckets (Execute in Storage UI, but documenting here)
-- Bucket: 'avatars', 'memories'
